"use client";

import { useId, useState } from "react";
import { Hash, Loader2, Plus } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { CATALOG_LIMITS, type CatalogCategory } from "@/lib/catalogo/domain";
import type { ProductFormErrors, ProductFormState } from "@/lib/catalogo/form";
import type { CatalogClient } from "@/lib/catalogo-client";
import { CField, PriceInput, ReferenceTag, StockInput, cn, inputCls } from "@/components/dashboard/catalogo/ui";

/** Referencia: SIEMPRE de solo lectura. Antes de guardar se explica que la genera DuLabs. */
export function ReferenceField({ reference }: { reference: string | null }) {
  const { t } = useI18n();
  return (
    <div className="flex items-center gap-3 rounded-xl border border-dashed border-edge bg-ink-2/60 px-4 py-3">
      <div className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-card text-lime-text">
        <Hash className="size-4" />
      </div>
      <div className="min-w-0 flex-1">
        <p className="text-[11px] font-medium uppercase tracking-widest text-mist">{t("Referencia", "Reference")}</p>
        {reference ? (
          <div className="mt-1 flex items-center gap-2">
            <ReferenceTag reference={reference} copyable size="lg" />
            <span className="text-xs text-mist">{t("No editable", "Read-only")}</span>
          </div>
        ) : (
          <p className="mt-0.5 text-sm text-fg">{t("Generada automáticamente por DuLabs", "Automatically generated by DuLabs")}</p>
        )}
      </div>
    </div>
  );
}

function CategorySelect({
  id,
  value,
  onChange,
  categories,
  onCreated,
  client,
  disabled,
  canCreate,
}: {
  id: string;
  value: string | null;
  onChange: (id: string | null) => void;
  categories: CatalogCategory[];
  onCreated: (c: CatalogCategory) => void;
  client: CatalogClient | null;
  disabled?: boolean;
  canCreate: boolean;
}) {
  const { t } = useI18n();
  const [creating, setCreating] = useState(false);
  const [name, setName] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const crear = async () => {
    if (!client || !name.trim()) return;
    setBusy(true);
    setError(null);
    const r = await client.createCategory(name.trim());
    setBusy(false);
    if (!r.ok) {
      setError(r.error.message);
      return;
    }
    onCreated(r.data.category);
    onChange(r.data.category.id);
    setCreating(false);
    setName("");
  };

  if (creating) {
    return (
      <div>
        <div className="flex gap-2">
          <input
            id={id}
            autoFocus
            className={inputCls}
            value={name}
            maxLength={60}
            placeholder={t("Ej. Dijes", "e.g. Pendants")}
            onChange={(e) => setName(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                void crear();
              }
              if (e.key === "Escape") setCreating(false);
            }}
          />
          <button type="button" onClick={crear} disabled={busy || !name.trim()} className="flex shrink-0 items-center gap-1.5 rounded-lg bg-lime px-3 text-sm font-medium text-lime-fg transition-opacity hover:opacity-90 disabled:opacity-50">
            {busy ? <Loader2 className="size-4 animate-spin" /> : t("Crear", "Create")}
          </button>
          <button type="button" onClick={() => setCreating(false)} className="shrink-0 px-2 text-sm text-mist hover:text-fg">
            {t("Cancelar", "Cancel")}
          </button>
        </div>
        {error && <p className="mt-1 text-xs text-red-400">{error}</p>}
      </div>
    );
  }

  return (
    <div className="flex gap-2">
      <select id={id} className={cn(inputCls, "appearance-none")} value={value ?? ""} disabled={disabled} onChange={(e) => onChange(e.target.value || null)}>
        <option value="">{t("Sin categoría", "No category")}</option>
        {categories.map((c) => (
          <option key={c.id} value={c.id}>
            {c.name}
          </option>
        ))}
      </select>
      {canCreate && !disabled && (
        <button
          type="button"
          onClick={() => setCreating(true)}
          className="flex shrink-0 items-center gap-1 rounded-lg border border-edge px-3 text-sm text-mist transition-colors hover:border-lime/40 hover:text-fg"
          title={t("Nueva categoría", "New category")}
        >
          <Plus className="size-4" />
          <span className="hidden sm:inline">{t("Nueva", "New")}</span>
        </button>
      )}
    </div>
  );
}

export function ProductFields({
  value,
  onChange,
  errors,
  categories,
  onCategoryCreated,
  client,
  disabled,
  stockUntracked,
}: {
  value: ProductFormState;
  onChange: (v: ProductFormState) => void;
  errors: ProductFormErrors;
  categories: CatalogCategory[];
  onCategoryCreated: (c: CatalogCategory) => void;
  client: CatalogClient | null;
  disabled?: boolean;
  /** Producto legado que aún no controla inventario (el stock es opcional hasta definirlo). */
  stockUntracked?: boolean;
}) {
  const { t } = useI18n();
  const ids = useId();
  const set = <K extends keyof ProductFormState>(key: K, v: ProductFormState[K]) => onChange({ ...value, [key]: v });

  return (
    <div className="space-y-4">
      <CField label={t("Nombre", "Name")} htmlFor={`${ids}-name`} required>
        <input
          id={`${ids}-name`}
          className={cn(inputCls, errors.name && "border-red-500/60")}
          value={value.name}
          maxLength={120}
          disabled={disabled}
          placeholder={t("Ej. Dije corazón en oro laminado", "e.g. Gold-plated heart pendant")}
          aria-invalid={Boolean(errors.name) || undefined}
          onChange={(e) => set("name", e.target.value)}
        />
        {errors.name && <p className="mt-1 text-xs text-red-400">{errors.name}</p>}
      </CField>

      <CField label={t("Categoría", "Category")} htmlFor={`${ids}-category`}>
        <CategorySelect
          id={`${ids}-category`}
          value={value.categoryId}
          onChange={(id) => set("categoryId", id)}
          categories={categories}
          onCreated={onCategoryCreated}
          client={client}
          disabled={disabled}
          canCreate={!disabled}
        />
      </CField>

      <div className="grid gap-4 sm:grid-cols-2">
        <CField label={t("Precio detal", "Retail price")} htmlFor={`${ids}-retail`} required>
          <PriceInput id={`${ids}-retail`} value={value.retailPrice} onChange={(v) => set("retailPrice", v)} placeholder="35.000" disabled={disabled} invalid={Boolean(errors.retailPrice)} />
          {errors.retailPrice && <p className="mt-1 text-xs text-red-400">{errors.retailPrice}</p>}
        </CField>
        <CField label={t("Precio mayor", "Wholesale price")} htmlFor={`${ids}-wholesale`} hint={t("Opcional. El mismo producto, precio al por mayor.", "Optional. Same product, wholesale price.")}>
          <PriceInput id={`${ids}-wholesale`} value={value.wholesalePrice} onChange={(v) => set("wholesalePrice", v)} placeholder="18.000" disabled={disabled} invalid={Boolean(errors.wholesalePrice)} />
          {errors.wholesalePrice && <p className="mt-1 text-xs text-red-400">{errors.wholesalePrice}</p>}
        </CField>
      </div>

      <CField
        label={t("Stock disponible", "Available stock")}
        htmlFor={`${ids}-stock`}
        required={!stockUntracked}
        hint={
          stockUntracked && value.stock === null
            ? t(
                "Cantidad disponible para venta. Este producto aún no controla inventario: al definirla, el catálogo mostrará la disponibilidad real.",
                "Quantity available for sale. This product doesn't track inventory yet: once set, the catalog will show real availability.",
              )
            : t("Cantidad disponible para venta.", "Quantity available for sale.")
        }
      >
        <div className="sm:max-w-[calc(50%-0.5rem)]">
          <StockInput id={`${ids}-stock`} value={value.stock} onChange={(v) => set("stock", v)} max={CATALOG_LIMITS.stock} disabled={disabled} invalid={Boolean(errors.stock)} />
        </div>
        {errors.stock && <p className="mt-1 text-xs text-red-400">{errors.stock}</p>}
      </CField>

      <div className="grid gap-4 sm:grid-cols-2">
        <CField label={t("Material", "Material")} htmlFor={`${ids}-material`}>
          <input id={`${ids}-material`} className={inputCls} value={value.material} maxLength={80} disabled={disabled} placeholder={t("Ej. Oro laminado 18k", "e.g. 18k gold-plated")} onChange={(e) => set("material", e.target.value)} />
        </CField>
        <CField label={t("Color", "Color")} htmlFor={`${ids}-color`}>
          <input id={`${ids}-color`} className={inputCls} value={value.color} maxLength={80} disabled={disabled} placeholder={t("Ej. Dorado", "e.g. Gold")} onChange={(e) => set("color", e.target.value)} />
        </CField>
      </div>

      <CField label={t("Descripción", "Description")} htmlFor={`${ids}-description`}>
        <textarea
          id={`${ids}-description`}
          className={cn(inputCls, "min-h-[88px] resize-y")}
          value={value.description}
          maxLength={1000}
          disabled={disabled}
          placeholder={t("Detalles que ayuden a vender: medidas, cierre, garantía…", "Details that help sell: size, clasp, warranty…")}
          onChange={(e) => set("description", e.target.value)}
        />
      </CField>
    </div>
  );
}
